name: CI

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build # Ensure packages pass attw, etc.
      - run: pnpm run -r build # Build packages/site
  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm dedupe --check --prefer-offline
  flint:
    name: Flint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run --filter=site prebuild # Generate packages/site/.astro
      - run: pnpm run flint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run --filter=site prebuild # Generate packages/site/.astro
      - run: pnpm run lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build # Knip requires all exports to be generated.
      - run: pnpm run lint:knip
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # required so origin/main can be diffed
      - uses: ./.github/actions/prepare
      - name: Cache dependencies and Vite cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules/.vite
      - run: pnpm exec tsc -b # For types tests
      - run: pnpm run build -W ./packages/ts-patch/ # vitest-dev/vitest#9429
      - # Run partial test pass on PRs (only changed files)
        if: ${{ github.event_name == 'pull_request' }}
        name: Run affected tests
        run: pnpm run test --changed "origin/main"
      - # On main, run the full test suite w/ type checking
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Run full test suite
        run: pnpm run test
